SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);

CREATE TABLE utilisateur (
	IdUtilisateur	INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Nom				VARCHAR(20)		NOT NULL, 
	Prenom			VARCHAR(20)		NOT NULL, 
	Mail			VARCHAR(50)		NOT NULL;
	Pseudo			VARCHAR(20)		NOT NULL,
	Mdp				VARCHAR(50)		NOT NULL, 
	Role			VARCHAR(20)		NOT NULL,
	Credit			INT				NOT NULL, 
	
	
	PRIMARY KEY (IdUtilisateur),
	FOREIGN KEY (Role) REFERENCES role (Role)

); 

CREATE TABLE produit (
	IdProduit		INT				NOT NULL		GENERATED BY DEFAULT AS IDENTITY, 
	IdUtilisateur	INT				NOT NULL, 
	Nom 			VARCHAR(20)		NOT NULL, 
	Description		VARCHAR(200), 
	PrixMin			INT				NOT NULL,
	DateDebut	DATE		NOT NULL, 
	HeureDebut	TIME		NOT NULL, 
	DateFin		DATE		NOT NULL, 
	HeureFin	TIME		NOT NULL
	
	PRIMARY KEY (IdProduit), 
	FOREIGN KEY (IdUtilisateur)	REFERENCES	utilisateur (IdUtilisateur)

); 

-- Création de la table mouvement
CREATE TABLE mouvement (
    idMouvement INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idUtilisateur INT,
    idProduit INT,
    type VARCHAR(255) NOT NULL,
    montant DOUBLE NOT NULL,
    date_heure TIMESTAMP NOT NULL,
    FOREIGN KEY (idUtilisateur) REFERENCES utilisateur(idUtilisateur),
    FOREIGN KEY (idProduit) REFERENCES produit(idProduit)
);
